= Creating Apache Fineract unit tests using OpenAI
:toc:

_Using the existing set of Apache Fineract unit tests, fine tune an OpenAI model using the OpenAI API to generate additional and replacement unit tests._

== Set Up

Note that the following set up instructions use a Fedora Linux instance. They may need to be adjusted depending on your operating system.

1. Download the code from this repository. Note this includes the test files under `training/facts`.
1. Get your OpenAI API key and add it to your environment.

    $ export OPENAI_API_KEY=<YOUR_KEY>

1. Enter the code repo directory and run the `toolbox` script. Note the requirement to add both your OPEN API key as well as an API secret.

    $ cd fineract-unit-tests-openai
    $ build_fineract-unit-tests-openai_toolbox.sh
    $ toolbox enter fineract-unit-tests-openai

== Converse with OpenAI API Chat using *.java files _contextually_

Note that this approach does not use a fine-tuned model but prompt engineering instead.

1. Train the model using the following command, followed by selecting `1` at the prompt.

    $ python3 main.py

1. Run the chat interfact using the same command, this time followed by selecting `2` at the prompt.

== Extracting unit test methods from Java test files

To extract unit tests run the following script:

    $ python3 export-method-names-bodies.py

This will extract the unit tests into a file called `output.json` in JSONL format. Each entry consists of a generated prompt/question and the expected response. 

== Folders

Note that:

* `training/``: contains all training files (i.e., *.java test files), any prompts, and trained model lists (i.e., `model-list.txt`).
* `results/`: contains results of tests.
* `archive/`: contains any files not used from previous iterations but kept around just in case.

== TODO

== Previous README

Additional information that may be useful in the future. Original README is https://replit.com/@DavidAtReplit/Custom-Company-Chatbot?v=1#README.md[located here].

=== JSON API (Advanced Users)

Option 3, or stating automatically after five seconds on the menu, is the JSON API. You can use POST requests to this Repl's repl.co address to take the chat to a different location or app.

Here's a quick guide to dealing with the API part in Python

    import requests

data to be sent to the server

    data = {'key': 'YOUR API KEY', 'question': 'Your question', 'history': 'previous questioning history'}

sending post request and saving response as response object

    r = requests.post(url = URL, data = data)

extracting response json

    response_data = r.json()

printing response

    print(response_data)

=== Credit

All based on the Amjad Masad Chat bot by IronCladDev on Replit For more information on how this works, check out Zahid Khawaja's Tutorial.
